# Unique name for this workflow
name: On push develop - Deploy to Dev2 Org

# Definition when the workflow should run
on:
    push:
        branches:
            - develop
        paths:
            - force-app/**

# Jobs to be executed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
        
    - name: Authenticate DevHub
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.SALESFORCE_DEVHUB_USERNAME}} --setdefaultdevhubusername -a targetorg
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}
        
    - name: Deploy source
      run: node_modules/sfdx-cli/bin/run force:source:deploy -u targetorg
